import { StyleSheet } from 'react-native'
import { StatusBar } from 'react-native';
import { SearchBar } from 'react-native-screens';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    backgroundColor: "white",
    width: '100%',
    paddingTop: StatusBar.currentHeight || 70,
  },
  insideContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    backgroundColor: "white",
    width: '100%',
  },
  polishedList: {
    width: '100%',
    flex: 1,
    backgroundColor: "white",
  },
  polishedListContent: {
    paddingHorizontal: 20,
    paddingBottom: 28,
  },
  postListWrap: {
    width: "100%",
    backgroundColor: "white",
  },
  polishedRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    paddingVertical: 14,
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderBottomColor: "#eeeeee",
  },
  polishedRowMain: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
  },
  polishedRowTitle: {
    color: "black",
    fontSize: 17,
    fontWeight: "bold",
    backgroundColor: "white",
  },
  polishedRowMeta: {
    color: "gray",
    fontSize: 14,
    marginTop: 3,
    backgroundColor: "white",
  },
  polishedScoreBadge: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderColor: "lightgray",
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "white",
    marginLeft: 12,
  },
  polishedScoreText: {
    color: "#2D5A3D",
    fontSize: 17,
    fontWeight: "bold",
    backgroundColor: "white",
  },
  polishedIconCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#eef5f0",
    marginRight: 12,
  },
  stateContainer: {
    width: "100%",
    flex: 1,
    minHeight: 180,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 28,
    paddingVertical: 36,
    backgroundColor: "white",
  },
  stateInline: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    paddingVertical: 28,
    backgroundColor: "white",
  },
  stateIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#eef5f0",
    marginBottom: 10,
  },
  stateTitle: {
    color: "black",
    fontSize: 17,
    fontWeight: "bold",
    textAlign: "center",
    backgroundColor: "white",
    marginBottom: 4,
  },
  stateText: {
    color: "gray",
    fontSize: 15,
    lineHeight: 21,
    textAlign: "center",
    backgroundColor: "white",
  },
  stateRetryButton: {
    marginTop: 14,
    borderWidth: 1,
    borderColor: "#2D5A3D",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: "white",
  },
  stateRetryText: {
    color: "#2D5A3D",
    fontSize: 14,
    fontWeight: "600",
    backgroundColor: "white",
  },
  feedActionButton: {
    minWidth: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 4,
    paddingHorizontal: 6,
    backgroundColor: "white",
  },
  postActionCount: {
    color: "black",
    fontSize: 14,
    fontWeight: "600",
    backgroundColor: "white",
  },
  postCard: {
    flexDirection: "column",
    gap: 10,
    width: "100%",
    paddingVertical: 16,
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderBottomColor: "#eeeeee",
  },
  postHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
    backgroundColor: "white",
  },
  postAuthorRow: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    marginRight: 10,
  },
  postImage: {
    borderRadius: 8,
    width: "100%",
    height: 220,
    zIndex: 2,
    backgroundColor: "#f1f1f1",
  },
  postNotes: {
    backgroundColor: "white",
    color: "black",
    fontSize: 15,
    lineHeight: 21,
  },
  postActions: {
    flexDirection: "row",
    backgroundColor: "white",
    gap: 4,
  },
  tasteProfileWrap: {
    width: "100%",
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 28,
    backgroundColor: "white",
    gap: 18,
  },
  tasteSection: {
    width: "100%",
    backgroundColor: "white",
  },
  tasteSectionTitle: {
    color: "black",
    fontFamily: "serif",
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 4,
    backgroundColor: "white",
  },
  tasteRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    paddingVertical: 14,
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderBottomColor: "#eeeeee",
  },
  tasteEmptyCard: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#eeeeee",
    borderRadius: 8,
    padding: 22,
    backgroundColor: "white",
  },
  tasteEmptyTitle: {
    color: "black",
    fontSize: 17,
    fontWeight: "bold",
    marginTop: 8,
    backgroundColor: "white",
  },
  tasteEmptyText: {
    color: "gray",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
    marginTop: 4,
    backgroundColor: "white",
  },
  rankingFilterScroller: {
    width: "100%",
    maxHeight: 50,
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderBottomColor: "#eeeeee",
  },
  rankingFilterContent: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    gap: 8,
    alignItems: "center",
  },
  rankingFilterChip: {
    borderWidth: 1,
    borderColor: "#dfe7e2",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 5,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
  },
  rankingFilterChipActive: {
    borderWidth: 1,
    borderColor: "#2D5A3D",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 5,
    backgroundColor: "#2D5A3D",
    alignItems: "center",
    justifyContent: "center",
  },
  rankingFilterText: {
    color: "black",
    fontSize: 14,
    fontWeight: "600",
    backgroundColor: "white",
  },
  rankingFilterTextActive: {
    color: "white",
    fontSize: 14,
    fontWeight: "600",
    backgroundColor: "#2D5A3D",
  },
  editModalSurface: {
    backgroundColor: "white",
    padding: 20,
    paddingTop: 16,
    gap: 14,
  },
  editProfileImageWrap: {
    alignSelf: "center",
    width: 108,
    height: 108,
    borderRadius: 54,
    borderWidth: 1,
    borderColor: "lightgray",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f7faf8",
    marginBottom: 2,
  },
  editPhotoButton: {
    alignSelf: "center",
    borderWidth: 1,
    borderColor: "#2D5A3D",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "white",
    marginBottom: 4,
  },
  editPhotoText: {
    color: "#2D5A3D",
    fontSize: 14,
    fontWeight: "600",
    backgroundColor: "white",
  },
  searchBox: {
    backgroundColor: "white",
    padding: 20,
    shadowOpacity: 0.1,
    
    height: 75,
    width: '100%',
  },
  searchBoxGoogle: {
    backgroundColor: "white",
    flex: 1,
    padding: 20,
    
    width: '100%',
    zIndex: 11,
  },
  restaurantSearch: {
    backgroundColor: "lightgray",
    borderColor: "lightgray",
    borderRadius: 8,
    padding: 8,
    borderBottomWidth: 1,
    display: 'flex',
    flexDirection: 'row',
    height: 40,
    width: '100%',
    alignSelf: 'center',
    alignItems: 'center',
  },
  searchPlaceholder: {
    color: "gray",
    fontSize: 16,
  },
  loginContainer: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    backgroundColor: "white",
    width: '100%',
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: StatusBar.currentHeight || 70,
    gap: 12,
  },
  landingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: "white",
  },
  title: {
    fontSize: 40,
    fontWeight: 'bold',
    fontFamily: 'georgia',
    backgroundColor: "clear",
    color: "black"
  },
  landingTitle: {
    fontSize: 50,
    fontWeight: 400,
    backgroundColor: "clear",
    color: "white",
    textAlign: 'center',
    fontFamily: 'georgia',
    marginBottom: 20,
  },
  separator: {
    marginVertical: 10,
    height: 1,
    width: '100%',
    backgroundColor: "white",
    color: "black"
  },
  mainInput: {
    backgroundColor: "white",
    borderColor: "grey",
    borderRadius: 8,
    padding: 8,
    borderBottomWidth: 1,
    marginBottom: 12,
    height: 50,
    width: '100%',
  },
  gradientBackground: {
    flex: 1,
    justifyContent: 'center',
  },
  
  gradientBackgroundCafe: {
    flex: 1,
    justifyContent: 'center',
    height: 300,
    backgroundColor: 'clear',
    marginBottom: 5,
  },
  imageBackgroundCafe: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    padding: 20,
  },
  cafeTitle: {
    fontFamily: 'georgia',
    fontSize: 48,
    fontWeight: 500,
    color: 'black',
    alignSelf: 'flex-start',
    marginBottom: 10,
  },
  avgRankingWrapper: {
    width: 30,
    height: 25,
    backgroundColor: '#00bf63',
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  avgRanking: {
    color: 'white',
    fontFamily: 'arial',
    fontWeight: 500,
    fontSize: 17,
  },
  numReviews: {
    fontSize: 16,
    fontWeight: 500,
    color: '#2D5A3D',
    fontFamily: 'arial'
  },
  cafeRankings: {
    flexDirection: 'row',
    justifyContent: 'space-between'
  },
  cafeRankingStats: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center'
  },
  cafeActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    
  },
  cafeContacts: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 15,
  },
  cafeAddress: {
    fontFamily: 'georgia',
    fontWeight: 500,
    color: '#2D5A3D',
    fontSize: 16,
    marginBottom: 15,
  },
  cafeWebsite: {
    width: 90,
    height: 32,
    borderWidth: 1,
    borderRadius: 16,
    borderColor: '#2D5A3D',
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row'
  },
  cafeWebsiteText: {
    color: '#2D5A3D',
    fontFamily: 'arial',
    fontSize: 18,
  },
  cafeNumber: {
    width: 70,
    height: 30,
    borderWidth: 1,
    borderRadius: 16,
    borderColor: '#2D5A3D',
    backgroundColor: 'white'
  },
  scoreCards: {
    gap: 10,
  },
  scoreCardContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  scoreContainer: {
    width: 55,
    height: 55,
    borderRadius: 100,
    borderColor: "gray",
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 5,
  },
  scoreContainerSmall: {
    width: 40,
    height: 40,
    borderRadius: 100,
    borderColor: "gray",
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 5,
  },
  scoreContainerSmallInside: {
    width: 40,
    height: 40,
    borderRadius: 100,
    borderColor: "gray",
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 5,
    backgroundColor: "white"
  },
  scoreCardRateSmall: {
    fontFamily: "serif",
    fontSize: 18,
    fontWeight: 600,
    color: "#109755"
  },
  scoreCardRate: {
    fontFamily: "serif",
    fontSize: 28,
    fontWeight: 600,
    color: "#109755"
  },
  scoreCardSecondaryText: {
    fontFamily: "serif",
    fontSize: 16,
    fontWeight: 600,
  },
  imageBackground: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingTop: 100,
    paddingBottom: 100,
  },
  secondary: {
    fontSize: 20,
    fontWeight: 'normal',
    backgroundColor: "clear",
    color: "white",
    fontFamily: 'arial',
  },
  largeLogo: {
    width: 130,
    height: 130,
    marginBottom: 20,
  },
  profileImage: {
    alignSelf: 'center',
    width: 100,
    height: 100,
    borderRadius: 50,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "lightgray",
  },
  profileImageSmall: {
    alignSelf: 'center',
    width: 70,
    height: 70,
    borderRadius: 50,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "lightgray",
  },
  profileImageSmaller: {
    alignSelf: 'center',
    width: 50,
    height: 50,
    borderRadius: 50,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "lightgray",
  },
  largeButton: {
    backgroundColor: "#2D5A3D",
    color: "white",
    borderRadius: 32,
    padding: 12,
    marginBottom: 8,
    height: 50,
    width: '85%',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  largeBackButton: {
    backgroundColor: "lightgrey",
    color: "white",
    borderRadius: 32,
    padding: 12,
    marginBottom: 8,
    height: 50,
    width: '85%',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  topPadding: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: '100%',
  },
  bottomPadding: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    width: '100%',
  },
  backButton: {
    alignSelf: 'flex-start',
  },
  username: {
    fontSize: 20,
    fontWeight: 'bold',
    backgroundColor: "clear",
    color: "black",
    fontFamily: 'arial',
    marginBottom: 10,
  },
  bioText: {
    fontSize: 16,
    fontWeight: 'normal',
    backgroundColor: "clear",
    color: "black",
    fontFamily: 'arial',
    marginBottom: 24,
  },
  profileInfo: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '80%',
    marginBottom: 20,
    backgroundColor: "white",
    color: "black"
  },
  profileInfoItem: {
    alignItems: 'center',
    backgroundColor: 'white',
  },
  profileInfoNum: {
    fontSize: 20,
    fontWeight: 'bold',
    backgroundColor: "white",
    color: "black",
    fontFamily: 'arial',
    marginBottom: 5,
  },
  profileInfoText: {
    fontSize: 16,
    fontWeight: 'normal',
    backgroundColor: "white",
    color: "gray",
    fontFamily: 'arial',
  },
  profileButton: {
    backgroundColor: "white",
    color: "black",
    borderColor: "#dfe7e2",
    borderWidth: 1,
    borderRadius: 16,
    padding: 0,
    marginBottom: 8,
    height: 34,
    width: '60%',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  profileButtonMatcha: {
    backgroundColor: "#2D5A3D",
    borderColor: "#2D5A3D",
  },
  profileButtonText: {
    color: "black",
    fontSize: 16,
    fontWeight: "600",
    backgroundColor: "transparent",
  },
  profileButtonTextLight: {
    color: "white",
    fontSize: 16,
    fontWeight: "600",
    backgroundColor: "transparent",
  },
  searchTabs: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    zIndex: 10,
  },
  activeTab: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderColor: "#2D5A3D",
    width: '50%',
    height: 40,
  },
  activeTabText: {
    color: "#2D5A3D",
    fontWeight: 'bold',
    fontSize: 16,
  },
  inactiveTab: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: "white",
    justifyContent: 'center',
    borderColor: "clear",
    width: '50%',
    height: 40,
  },
  inactiveTabText: {
    color: "black",
    fontWeight: 'bold',
    fontSize: 16,
  },
  backdropContainer: {
    flex: 1,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
  },
  rankingModal: {
    width: "100%",
    padding: 15,
    paddingBottom: 30,
  },
  modalTitle: {
    flex: 1,
    marginBottom: 6,
    borderRadius: 16,
    backgroundColor: "white",
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 15,
    alignItems: "center",
  },
  modalTitleText: {
    fontSize: 28,
    fontFamily: 'Georgia',
    fontWeight: 600,
  },
  modalCategory: {
    flex: 1,
    marginVertical: 6,
    borderRadius: 16,
    backgroundColor: "white",
    padding: 15,
    gap: 10,
    shadowColor: "#000",
    shadowOffset: {
        width: 0,
        height: 0,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,

    elevation: 3,
  },
  modalText: {
    fontSize: 18,
    fontFamily: 'arial',
  },
  selectText: {
    color: "white",
    fontFamily: "arial",
    fontSize: 16,
  },
  nonSelectText: {
    color: "black",
    fontFamily: "arial",
    fontSize: 16,
  },
  drinkCategory: {
    height: 40, 
    width: 120, 
    marginHorizontal: 5, 
    flexDirection: "row", 
    alignItems: "center", 
    justifyContent: "center", 
    borderWidth: 1, 
    borderColor: "#2D5A3D", 
    borderRadius: 12
  },
  drinkCategorySelect: {
    height: 40, 
    width: 120, 
    marginHorizontal: 5, 
    flexDirection: "row", 
    alignItems: "center", 
    justifyContent: "center", 
    backgroundColor: "#2D5A3D",
    borderRadius: 12
  },
  drinkText: {
    fontFamily: "serif",
    fontSize: 16,
  },
  drinkTextSelected: {
    fontFamily: "serif",
    fontSize: 16,
    color: "white"
  },
  submitModal: {
    width: "80%",
    marginVertical: 6,
    justifyContent: "center",
    alignItems: "center",
    padding: 10,
    borderRadius: 16,
    backgroundColor: "#2D5A3D",
    gap: 10,
    shadowColor: "#000",
    shadowOffset: {
        width: 0,
        height: 0,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,

    elevation: 3,
    alignSelf: "center",
    marginBottom: 30,
  },
});
