import { StyleSheet } from 'react-native'
import { StatusBar } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    backgroundColor: "white",
    width: '100%',
    paddingTop: StatusBar.currentHeight || 70,
  },
  loginContainer: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    backgroundColor: "white",
    width: '100%',
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: StatusBar.currentHeight || 70,
    gap: 12,
  },
  landingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: "white",
  },
  title: {
    fontSize: 40,
    fontWeight: 'bold',
    fontFamily: 'georgia',
    backgroundColor: "clear",
    color: "black"
  },
  landingTitle: {
    fontSize: 50,
    fontWeight: 400,
    backgroundColor: "clear",
    color: "white",
    textAlign: 'center',
    fontFamily: 'georgia',
    marginBottom: 20,
  },
  separator: {
    marginVertical: 30,
    height: 1,
    width: '80%',
    backgroundColor: "white",
    color: "black"
  },
  mainInput: {
    backgroundColor: "white",
    borderColor: "grey",
    borderRadius: 8,
    padding: 8,
    borderBottomWidth: 1,
    marginBottom: 12,
    height: 50,
    width: '100%',
  },
  gradientBackground: {
    flex: 1,
    justifyContent: 'center',
  },
  imageBackground: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingTop: 100,
    paddingBottom: 100,
  },
  secondary: {
    fontSize: 20,
    fontWeight: 'normal',
    backgroundColor: "clear",
    color: "white",
    fontFamily: 'arial',
  },
  largeLogo: {
    width: 130,
    height: 130,
    marginBottom: 20,
  },
  profileImage: {
    alignSelf: 'center',
    width: 100,
    height: 100,
    borderRadius: 50,
    marginBottom: 20,
  },
  largeButton: {
    backgroundColor: "#2D5A3D",
    color: "white",
    borderRadius: 32,
    padding: 12,
    marginBottom: 8,
    height: 50,
    width: '85%',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  largeBackButton: {
    backgroundColor: "lightgrey",
    color: "white",
    borderRadius: 32,
    padding: 12,
    marginBottom: 8,
    height: 50,
    width: '85%',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  topPadding: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: '100%',
  },
  bottomPadding: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    width: '100%',
  },
  backButton: {
    alignSelf: 'flex-start',
  },
});